// opencode-notify:plugin
// Generated by opencode-notify (Go). Do not edit by hand.
// Reinstall with: opencode-notify install
const NOTIFY_CMD_BASE = __NOTIFY_CMD_JSON__;
const NOTIFY_CMD_ENV = process.env.OPENCODE_NOTIFY_BIN;
const NOTIFY_CMD = NOTIFY_CMD_ENV
  ? [NOTIFY_CMD_ENV, ...NOTIFY_CMD_BASE.slice(1)]
  : NOTIFY_CMD_BASE;
const DEDUPE_MS = 1500;

let lastEventKey = '';
let lastEventAt = 0;

function firstString(...values) {
  for (const value of values) {
    if (typeof value === 'string' && value.trim()) return value.trim();
  }
  return '';
}

function getEventType(event) {
  return firstString(event && event.type);
}

function getSessionId(event) {
  const props = event && typeof event.properties === 'object' ? event.properties : {};
  return firstString(
    event && event.sessionID,
    event && event.sessionId,
    props.sessionID,
    props.sessionId,
    props.id,
  );
}

function getErrorMessage(event) {
  const props = event && typeof event.properties === 'object' ? event.properties : {};
  const directError = event && typeof event.error === 'object' ? event.error : {};
  const propError = props && typeof props.error === 'object' ? props.error : {};
  return firstString(
    directError && directError.message,
    propError && propError.message,
    props.message,
    event && event.message,
  );
}

function getQuestionText(event) {
  if (typeof event !== 'object' || event === null) return '';
  const props = typeof event.properties === 'object' && event.properties !== null ? event.properties : {};
  const questions = Array.isArray(props.questions) ? props.questions : [];
  for (const item of questions) {
    if (typeof item !== 'object' || item === null) continue;
    const text = firstString(item.question, item.header, item.text);
    if (text) return text;
  }
  // Fallback for event shapes that carry the question directly.
  return firstString(props.question, props.text, props.content);
}

function delay(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function normalizeText(value) {
  return typeof value === 'string' ? value.replace(/\r\n/g, '\n').trim() : '';
}

function appendText(parts, value) {
  const text = normalizeText(value);
  if (text) parts.push(text);
}

function isVisibleTextPart(part) {
  if (!part || typeof part !== 'object') return false;
  const type = firstString(part.type, part.kind).toLowerCase();
  if (!type) return true;
  if (type !== 'text') return false;
  return part.ignored !== true;
}

function appendMessageParts(parts, messageParts) {
  if (!Array.isArray(messageParts)) return;
  for (const part of messageParts) {
    if (!isVisibleTextPart(part)) continue;
    appendText(parts, part.text);
    appendText(parts, part.content);
    appendText(parts, part.value);
  }
}

function extractMessageText(entry) {
  const parts = [];
  const entryParts = Array.isArray(entry && entry.parts) ? entry.parts : null;
  appendMessageParts(parts, entryParts);

  const message = entry && typeof entry.message === 'object' ? entry.message : null;
  const messageParts = message && Array.isArray(message.parts) ? message.parts : null;
  if (message) {
    appendMessageParts(parts, messageParts);
  }

  const hasStructuredParts = Boolean(entryParts || messageParts);
  if (!hasStructuredParts) {
    if (message) {
      appendText(parts, message.text);
      appendText(parts, message.content);
    }
    appendText(parts, entry && entry.text);
    appendText(parts, entry && entry.content);
    appendText(parts, typeof (entry && entry.message) === 'string' ? entry.message : '');
  }

  return parts.join('\n\n').trim();
}

function isAssistantMessage(entry) {
  const info = entry && typeof entry.info === 'object' ? entry.info : {};
  const role = firstString(info.role, entry && entry.role).toLowerCase();
  const kind = firstString(info.type, entry && entry.type).toLowerCase();
  return role === 'assistant' || kind === 'assistant';
}

function toMessageList(result) {
  if (Array.isArray(result)) return result;
  if (Array.isArray(result && result.data)) return result.data;
  if (Array.isArray(result && result.messages)) return result.messages;
  if (result && Array.isArray(result.data && result.data.messages)) return result.data.messages;
  return [];
}

async function fetchSessionDirectory(client, sessionId) {
  if (!client || !client.session || typeof client.session.get !== 'function' || !sessionId) {
    return '';
  }
  try {
    const result = await client.session.get({ path: { id: sessionId } });
    const session = result && result.data ? result.data : result;
    return firstString(session && session.directory);
  } catch (_error) {
    // ignore
  }
  return '';
}

async function fetchLatestAssistantText(client, sessionId) {
  if (!client || !client.session || typeof client.session.messages !== 'function' || !sessionId) {
    return '';
  }

  for (const waitMs of [0, 150, 500]) {
    if (waitMs > 0) {
      await delay(waitMs);
    }

    try {
      const result = await client.session.messages({ path: { id: sessionId } });
      const messages = toMessageList(result);
      for (let index = messages.length - 1; index >= 0; index -= 1) {
        const entry = messages[index];
        if (!isAssistantMessage(entry)) continue;
        const text = extractMessageText(entry);
        if (text) return text;
      }
    } catch (_error) {
      // ignore
    }
  }

  return '';
}

function isSessionIdleStatus(event) {
  if (getEventType(event) !== 'session.status') return false;
  const props = event && typeof event.properties === 'object' ? event.properties : {};
  const status = props.status;
  return status && typeof status === 'object' && status.type === 'idle';
}

const QUESTION_EVENT_TYPES = new Set(['question.asked', 'question.v2.asked']);

function isQuestionEvent(event) {
  return QUESTION_EVENT_TYPES.has(getEventType(event));
}

function isCompletionEvent(event) {
  const type = getEventType(event);
  if (type === 'session.idle') return true;
  if (type === 'session.error') return true;
  if (isQuestionEvent(event)) return true;
  return isSessionIdleStatus(event);
}

function truncateAssistantText(text, maxWords) {
  const value = normalizeText(text);
  if (!value) return '';
  const words = value.split(/\s+/).filter(Boolean);
  if (words.length <= maxWords) return value;
  return `${words.slice(0, maxWords).join(' ')}...`;
}

async function buildPayload(event, context, client) {
  const eventType = getEventType(event);
  const errorMessage = getErrorMessage(event);
  const sessionId = getSessionId(event);
  const questionText = isQuestionEvent(event) ? getQuestionText(event) : '';
  const [assistantText, sessionDir] = await Promise.all([
    (eventType === 'session.idle' || isSessionIdleStatus(event)) && !questionText
      ? fetchLatestAssistantText(client, sessionId)
      : '',
    fetchSessionDirectory(client, sessionId),
  ]);
  let taskInfo;
  let outputContent;
  if (eventType === 'session.error') {
    taskInfo = errorMessage ? `OpenCode 失败: ${errorMessage}` : 'OpenCode 失败';
    outputContent = errorMessage;
  } else if (questionText) {
    taskInfo = truncateAssistantText(`OpenCode 需要你回答: ${questionText}`, 50);
    outputContent = questionText;
  } else {
    taskInfo = truncateAssistantText(assistantText, 40) || 'OpenCode 完成';
    outputContent = assistantText;
  }
  return {
    hook_source: 'opencode-plugin',
    hook_event_name: eventType,
    cwd: firstString(
      sessionDir,
      event && event.cwd,
      event && event.directory,
      context.worktree,
      context.directory,
    ),
    task_info: taskInfo,
    session_id: sessionId,
    error_message: errorMessage,
    project_name: firstString(context.project && context.project.name),
    assistant_message: assistantText,
    question_text: questionText,
    output_content: outputContent,
  };
}

function shouldSkip(payload) {
  const key = [payload.hook_event_name, payload.session_id, payload.error_message].join('::');
  const now = Date.now();
  if (key && key === lastEventKey && now - lastEventAt < DEDUPE_MS) {
    return true;
  }
  lastEventKey = key;
  lastEventAt = now;
  return false;
}

async function dispatchPayload(payload) {
  const payloadJson = JSON.stringify(payload);
  try {
    Bun.spawn({
      cmd: NOTIFY_CMD,
      cwd: payload.cwd || undefined,
      env: {
        ...process.env,
        DESKTOP_NOTIFY_MODE: process.platform === 'win32' ? 'popup' : String(process.env.DESKTOP_NOTIFY_MODE || ''),
      },
      stdin: new TextEncoder().encode(payloadJson),
      stdout: 'ignore',
      stderr: 'ignore',
    });
  } catch (_error) {
    // ignore
  }
}

export const OpenCodeNotifyPlugin = async ({ client, project, directory, worktree }) => {
  return {
    event: async ({ event }) => {
      if (!isCompletionEvent(event)) return;

      const payload = await buildPayload(event, { project, directory, worktree }, client);
      if (shouldSkip(payload)) return;
      await dispatchPayload(payload);
    },
  };
};