// opencode-notify:plugin
// Generated by opencode-notify (Go). Do not edit by hand.
// Reinstall with: opencode-notify install
//
// Target: OpenCode v2 plugin API (Promise flavor).
// Shape: `export default { id, setup }` (same as Plugin.define, no import).
// Completion events are read from the OpenCode event stream:
//   - session.execution.succeeded / failed / interrupted  (authoritative)
//   - session.idle / session.error / session.status(idle)  (legacy, kept)
//   - form.created / question.asked / question.v2.asked    (waiting on input)
//   - permission.asked                                     (waiting on input)
//
// NOTE: this file deliberately does NOT import the plugin helper package
// (`@opencode/plugin`). A plugin directory outside the OpenCode install has no
// way to resolve that bare specifier (the loader only does a plain dynamic
// import), and its `Plugin.define` is only the identity function
// `(plugin) => plugin`. Exporting the plain `{ id, setup }` definition object
// is the same thing with zero dependencies.
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';

const NOTIFY_CMD_BASE = __NOTIFY_CMD_JSON__;
const NOTIFY_CMD_ENV = typeof process !== 'undefined' ? process.env.OPENCODE_NOTIFY_BIN : undefined;
const NOTIFY_CMD = NOTIFY_CMD_ENV ? [NOTIFY_CMD_ENV, ...NOTIFY_CMD_BASE.slice(1)] : NOTIFY_CMD_BASE;

// Per-session coalescing window: a burst of completion events (succeeded,
// failed, interrupted, idle, question) for the same session inside this window
// is collapsed into a single notification, preferring the most severe kind.
const COALESCE_MS = 1500;
const pendingBySession = new Map();

// Single-leader election: OpenCode boots one plugin instance per Location in
// the same server process, but completion events are server-wide. Without
// coordination every instance would spawn its own notify process for the same
// session (module-level maps are not shared across instances). Only the
// leader subscribes to the event stream; the rest stand by and promote
// themselves when the leader goes stale or its process dies.
const LEADER_LOCK_DIRNAME = 'plugin-leader.lock';
const LEADER_INFO_FILENAME = 'info.json';
const LEADER_HEARTBEAT_MS = 5000;
const LEADER_STALE_MS = 15000;

function stateDirectory() {
  const env = typeof process !== 'undefined' && process.env ? process.env : {};
  const override = (env.OPENCODE_NOTIFY_STATE_DIR || '').trim();
  if (override) return override;
  const xdg = (env.XDG_STATE_HOME || '').trim();
  if (xdg) return `${xdg.replace(/\/+$/, '')}/opencode-notify`;
  let home = (env.HOME || '').trim();
  if (!home) {
    try {
      home = homedir();
    } catch {
      home = '';
    }
  }
  if (home) return `${home.replace(/\/+$/, '')}/.local/state/opencode-notify`;
  return '';
}

function leaderPaths() {
  const dir = stateDirectory();
  if (!dir) return null;
  const lockDir = `${dir}/${LEADER_LOCK_DIRNAME}`;
  return { lockDir, infoPath: `${lockDir}/${LEADER_INFO_FILENAME}` };
}

function readLeaderInfo(infoPath) {
  try {
    return JSON.parse(readFileSync(infoPath, 'utf8'));
  } catch {
    return null;
  }
}

function leaderIsAlive(pid) {
  if (typeof pid !== 'number' || !Number.isFinite(pid) || pid <= 0) return false;
  try {
    process.kill(pid, 0);
    return true;
  } catch (err) {
    // ESRCH = dead; EPERM = alive but not ours.
    return Boolean(err && err.code === 'EPERM');
  }
}

function writeLeaderInfo(infoPath, location) {
  try {
    writeFileSync(
      infoPath,
      JSON.stringify({ pid: process.pid, location, updatedAt: Date.now() }),
    );
  } catch {
    // ignore
  }
}

// tryAcquireLeader atomically claims leadership via mkdir (fails with EEXIST
// when the lock dir already exists). An existing lock is stolen only when it
// is stale (no heartbeat) or its owner process is dead, so a previous server
// that exited without cleanup cannot wedge elections forever.
function tryAcquireLeader(location) {
  if (typeof process === 'undefined' || !process.pid) return true;
  const paths = leaderPaths();
  if (!paths) return true;
  try {
    mkdirSync(stateDirectory(), { recursive: true });
  } catch {
    return true;
  }
  try {
    mkdirSync(paths.lockDir);
    writeLeaderInfo(paths.infoPath, location);
    return true;
  } catch (err) {
    if (!err || err.code !== 'EEXIST') return true;
  }
  const info = readLeaderInfo(paths.infoPath);
  const fresh =
    info &&
    typeof info.updatedAt === 'number' &&
    Date.now() - info.updatedAt < LEADER_STALE_MS;
  if (fresh && (info.pid === process.pid || leaderIsAlive(info.pid))) return false;
  try {
    rmSync(paths.lockDir, { recursive: true, force: true });
    mkdirSync(paths.lockDir);
    writeLeaderInfo(paths.infoPath, location);
    return true;
  } catch {
    return false;
  }
}

function refreshLeaderHeartbeat(location) {
  if (typeof process === 'undefined' || !process.pid) return;
  const paths = leaderPaths();
  if (!paths) return;
  const info = readLeaderInfo(paths.infoPath);
  if (!info || info.pid !== process.pid) return;
  writeLeaderInfo(paths.infoPath, location);
}

function releaseLeader() {
  if (typeof process === 'undefined' || !process.pid) return;
  const paths = leaderPaths();
  if (!paths) return;
  const info = readLeaderInfo(paths.infoPath);
  if (!info || info.pid !== process.pid) return;
  try {
    rmSync(paths.lockDir, { recursive: true, force: true });
  } catch {
    // ignore
  }
}

function unrefTimer(timer) {
  try {
    if (timer && typeof timer.unref === 'function') timer.unref();
  } catch {
    // ignore
  }
}

function firstString(...values) {
  for (const value of values) {
    if (typeof value === 'string' && value.trim()) return value.trim();
  }
  return '';
}

function normalizeText(value) {
  return typeof value === 'string' ? value.replace(/\r\n/g, '\n').trim() : '';
}

// OpenCode v2 wraps every streamed event in an envelope
// `{ id, created, type, data }`. Legacy v1 events carried their fields under
// `properties`. Accept both shapes so this plugin survives either.
function envelope(event) {
  if (typeof event !== 'object' || event === null) return { type: '', data: {} };
  const type = firstString(event.type);
  const payload =
    typeof event.data === 'object' && event.data !== null
      ? event.data
      : typeof event.properties === 'object' && event.properties !== null
        ? event.properties
        : {};
  return { type, data: payload };
}

function getSessionId(event) {
  const { data } = envelope(event);
  return firstString(
    data.sessionID,
    data.sessionId,
    event && event.sessionID,
    event && event.sessionId,
    data.request && data.request.sessionID,
  );
}

function getErrorMessage(event) {
  const { data } = envelope(event);
  const error = data.error && typeof data.error === 'object' ? data.error : {};
  return firstString(
    error.message,
    typeof data.error === 'string' ? data.error : '',
    data.message,
    event && typeof event.error === 'object' && event.error ? event.error.message : '',
  );
}

// form.created carries a titled form with typed fields; pick the first visible
// field title (falling back to the form title) as the question text.
function getFormQuestion(data) {
  const title = firstString(data.form && data.form.title, data.title);
  const fields = Array.isArray(data.form && data.form.fields)
    ? data.form.fields
    : Array.isArray(data.fields)
      ? data.fields
      : [];
  for (const field of fields) {
    if (!field || typeof field !== 'object') continue;
    const text = firstString(field.title, field.description, field.key);
    if (text) return { question: text, title };
  }
  return { question: '', title };
}

// question.asked (v1-compatible) keeps questions under properties.questions.
function getAskedQuestion(data) {
  const questions = Array.isArray(data.questions) ? data.questions : [];
  for (const item of questions) {
    if (!item || typeof item !== 'object') continue;
    const text = firstString(item.question, item.header, item.text);
    if (text) return text;
  }
  return firstString(data.question, data.text, data.content);
}

const QUESTION_EVENT_TYPES = new Set(['question.asked', 'question.v2.asked', 'form.created']);

function isQuestionEvent(type) {
  return QUESTION_EVENT_TYPES.has(type);
}

function eventPriority(type) {
  if (type === 'session.execution.failed' || type === 'session.error') return 3;
  if (isQuestionEvent(type) || type === 'permission.asked') return 2;
  return 1;
}

function isCompletionEvent(type) {
  switch (type) {
    case 'session.execution.succeeded':
    case 'session.execution.failed':
    case 'session.execution.interrupted':
    case 'session.idle':
    case 'session.error':
    case 'permission.asked':
      return true;
    default:
      return isQuestionEvent(type) || isSessionIdleStatus(type, arguments[1]);
  }
}

function isSessionIdleStatus(type, event) {
  if (type !== 'session.status') return false;
  const { data } = envelope(event);
  const status = data.status;
  return Boolean(status && typeof status === 'object' && status.type === 'idle');
}

// The v2 plugin context exposes no session-message API (`ctx.session` has no
// `message.list`), so assistant text is accumulated from the event stream:
// `session.text.ended` carries the full text of each completed text part,
// keyed by sessionID. We keep the last few parts per session and clear them
// when a new execution starts.
const assistantTextBySession = new Map();
const MAX_TEXT_PARTS = 8;

function recordAssistantText(sessionId, text) {
  if (!sessionId || !text) return;
  const parts = assistantTextBySession.get(sessionId) || [];
  parts.push(text);
  while (parts.length > MAX_TEXT_PARTS) parts.shift();
  assistantTextBySession.set(sessionId, parts);
}

function takeAssistantText(sessionId) {
  if (!sessionId) return '';
  const parts = assistantTextBySession.get(sessionId) || [];
  assistantTextBySession.delete(sessionId);
  return parts.join('\n\n').trim();
}

function sessionDirectory(ctx, data, event) {
  return firstString(
    ctx && ctx.location && ctx.location.directory,
    data && data.directory,
    data && data.cwd,
    event && event.directory,
    event && event.cwd,
  );
}

function truncateWords(text, maxWords) {
  const value = normalizeText(text);
  if (!value) return '';
  const words = value.split(/\s+/).filter(Boolean);
  if (words.length <= maxWords) return value;
  return `${words.slice(0, maxWords).join(' ')}...`;
}

function baseName(path) {
  if (typeof path !== 'string' || !path) return '';
  const parts = path.replace(/\\/g, '/').split('/').filter(Boolean);
  return parts.length ? parts[parts.length - 1] : '';
}

// projectDisplayName prefers the human-readable project directory basename.
// ctx.location.project.id is a hex hash, not a display name, so it is never
// used here.
function projectDisplayName(ctx) {
  const location = (ctx && ctx.location) || {};
  const project = location.project || {};
  return firstString(
    baseName(project.directory),
    baseName(project.canonical),
    baseName(location.directory),
  );
}

// Best-effort session context lookup (title + owning directory) with a short
// timeout. The lookup must never delay or break the immediate first-event
// dispatch (non-interactive `opencode run` tears the process down fast), so
// any failure or slowness falls back to empty strings. The directory matters
// because only the elected leader subscribes: its ctx.location is the
// leader's project, not necessarily the finished session's.
const TITLE_FETCH_TIMEOUT_MS = 400;

function extractSessionTitle(response) {
  if (typeof response !== 'object' || response === null) return '';
  const candidates = [
    response.title,
    response.name,
    response.data && response.data.title,
    response.session && response.session.title,
    response.info && response.info.title,
  ];
  return firstString(...candidates);
}

function extractSessionDirectory(response) {
  if (typeof response !== 'object' || response === null) return '';
  const locations = [
    response.location,
    response.data && response.data.location,
    response.session && response.session.location,
    response.info && response.info.location,
  ];
  for (const location of locations) {
    if (location && typeof location.directory === 'string' && location.directory.trim()) {
      return location.directory.trim();
    }
  }
  const directories = [
    response.directory,
    response.cwd,
    response.data && (response.data.directory || response.data.cwd),
  ];
  return firstString(...directories);
}

async function fetchSessionContext(ctx, sessionId) {
  const empty = { title: '', directory: '' };
  if (!sessionId) return empty;
  const getters = [];
  if (ctx && ctx.session && typeof ctx.session.get === 'function') getters.push(ctx.session.get.bind(ctx.session));
  if (ctx && ctx.client && ctx.client.session && typeof ctx.client.session.get === 'function') {
    getters.push(ctx.client.session.get.bind(ctx.client.session));
  }
  if (!getters.length) return empty;
  const shapes = [{ sessionID: sessionId }, { path: { id: sessionId } }, { id: sessionId }];
  const lookup = (async () => {
    for (const get of getters) {
      for (const input of shapes) {
        try {
          const response = await get(input);
          const title = extractSessionTitle(response);
          const directory = extractSessionDirectory(response);
          if (title || directory) return { title, directory };
        } catch {
          // try the next shape
        }
      }
    }
    return empty;
  })();
  try {
    return await Promise.race([
      lookup,
      new Promise((resolve) => setTimeout(() => resolve(empty), TITLE_FETCH_TIMEOUT_MS)),
    ]);
  } catch {
    return empty;
  }
}

async function buildPayload(event, ctx) {
  const { type, data } = envelope(event);
  const sessionId = getSessionId(event);
  const errorMessage = getErrorMessage(event);

  let questionText = '';
  let formTitle = '';
  if (type === 'form.created') {
    const form = getFormQuestion(data);
    questionText = form.question;
    formTitle = form.title;
  } else if (type === 'question.asked' || type === 'question.v2.asked') {
    questionText = getAskedQuestion(data);
  } else if (type === 'permission.asked') {
    questionText = firstString(data.action, data.message, '需要授权');
  }

  const assistantText = questionText ? '' : takeAssistantText(sessionId);
  const sessionCtx = questionText ? { title: '', directory: '' } : await fetchSessionContext(ctx, sessionId);

  let taskInfo;
  let outputContent;
  let kind;
  if (type === 'session.execution.failed' || type === 'session.error') {
    kind = 'error';
    taskInfo = errorMessage ? `OpenCode 失败: ${errorMessage}` : 'OpenCode 失败';
    outputContent = errorMessage;
  } else if (questionText) {
    kind = 'question';
    taskInfo = truncateWords(`OpenCode 需要你回答: ${questionText}`, 50);
    outputContent = questionText;
  } else if (type === 'session.execution.interrupted') {
    kind = 'complete';
    taskInfo = 'OpenCode 已中断';
    outputContent = '';
  } else {
    kind = 'complete';
    taskInfo = truncateWords(assistantText, 40) || 'OpenCode 完成';
    outputContent = assistantText;
  }

  return {
    hook_source: 'opencode-plugin',
    hook_event_name: type,
    kind,
    cwd: firstString(sessionCtx.directory, sessionDirectory(ctx, data, event)),
    task_info: taskInfo,
    session_id: sessionId,
    session_title: sessionCtx.title,
    project_name: firstString(baseName(sessionCtx.directory), projectDisplayName(ctx)),
    error_message: errorMessage,
    assistant_message: assistantText,
    question_text: questionText,
    output_content: outputContent,
  };
}

function dispatchPayload(payload) {
  const payloadJson = JSON.stringify(payload);
  try {
    const spawn = globalThis.Bun && typeof globalThis.Bun.spawn === 'function' ? globalThis.Bun.spawn : undefined;
    if (!spawn) return;
    spawn({
      cmd: NOTIFY_CMD,
      cwd: payload.cwd || undefined,
      env: { ...process.env },
      stdin: new TextEncoder().encode(payloadJson),
      stdout: 'ignore',
      stderr: 'ignore',
    });
  } catch (_error) {
    // ignore
  }
}

// queueCoalesced collapses bursts of completion events per session. The first
// event for a session is dispatched immediately; further events for the same
// session are suppressed while a more/equally severe event is already in
// flight inside COALESCE_MS. It uses wall-clock bookkeeping instead of a
// `setTimeout`, because non-interactive runs (`opencode run`) tear the process
// down before any timer longer than ~0ms can fire.
function queueCoalesced(sessionKey, event, ctx) {
  const type = envelope(event).type;
  const priority = eventPriority(type);
  const now = Date.now();
  const existing = pendingBySession.get(sessionKey);
  if (existing && now - existing.at < COALESCE_MS && existing.priority >= priority) return;

  pendingBySession.set(sessionKey, { priority, at: now });
  void (async () => {
    try {
      dispatchPayload(await buildPayload(event, ctx));
    } catch (_error) {
      // ignore
    }
  })();
}

async function runEventLoop(ctx, events, signal) {
  try {
    for await (const event of events.subscribe({ signal })) {
      const { type, data } = envelope(event);
      if (!type) continue;
      const sessionId = getSessionId(event);
      if (type === 'session.text.ended') {
        recordAssistantText(sessionId, data.text);
        continue;
      }
      if (type === 'session.execution.started') {
        assistantTextBySession.delete(sessionId);
        continue;
      }
      if (!isCompletionEvent(type, event) && !isSessionIdleStatus(type, event)) continue;
      queueCoalesced(sessionId || 'global', event, ctx);
    }
  } catch (_error) {
    // stream closed or plugin unloaded
  }
}

export default {
  id: 'opencode-notify',
  async setup(ctx) {
    const events = ctx && ctx.event;
    if (!events || typeof events.subscribe !== 'function') return;
    const location = firstString(ctx && ctx.location && ctx.location.directory);
    const controller = new AbortController();
    const state = { leader: false, watcher: null, heartbeat: null };
    const activate = () => {
      if (state.leader) return;
      state.leader = true;
      if (state.watcher) {
        clearInterval(state.watcher);
        state.watcher = null;
      }
      refreshLeaderHeartbeat(location);
      state.heartbeat = setInterval(() => {
        refreshLeaderHeartbeat(location);
      }, LEADER_HEARTBEAT_MS);
      unrefTimer(state.heartbeat);
      void runEventLoop(ctx, events, controller.signal);
    };
    if (tryAcquireLeader(location)) {
      activate();
    } else {
      // Stand by: another Location instance in this server is the leader.
      // Promote ourselves if it goes stale or dies, so closing the leader's
      // project does not silently stop notifications.
      state.watcher = setInterval(() => {
        if (tryAcquireLeader(location)) activate();
      }, LEADER_HEARTBEAT_MS);
      unrefTimer(state.watcher);
    }
    // Cleanup: stop listening. Dispatched notifications are already in flight;
    // in-process bookkeeping can be dropped. Only the leader releases the
    // lock, and only when it still owns it.
    return () => {
      if (state.watcher) clearInterval(state.watcher);
      if (state.heartbeat) clearInterval(state.heartbeat);
      if (state.leader) releaseLeader();
      controller.abort();
      pendingBySession.clear();
      assistantTextBySession.clear();
    };
  },
};
